CREATE TABLE BLACKLIST(
ASN             BIGINT,
ASN_DESC        STRING,
IPADDRESS       BIGINT,
PROTOCOL        INT,
PORT            INT,
SUBNET          STRING,
DATEADDED       TIMESTAMP,
DATEOFINFO      TIMESTAMP,
DATEEXPIRES     TIMESTAMP,
CATEGORY        STRING,
COMMENTS        STRING,
SOURCE          STRING,
URL             STRING,
SHA1            STRING,
MD5             STRING,
DESCRIPTION     STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;