CREATE TABLE RATIONALIZATION(
IPADDRESS       BIGINT,
DATEADDED       TIMESTAMP,
DATEOFINFO      TIMESTAMP,
DATEEXPIRES     TIMESTAMP,
CATEGORY        STRING,
COMMENTS        STRING,
SOURCE          STRING,
URL             STRING,
DESCRIPTION     STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;